minimal_mistakes_skin    : "default" # 태마 색 설정 "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise" 

# Site Settings
locale                   : "ko-KR"
title                    : "Become Brave" # Meta 태그에 들어가는 영역 , masthead_title등이 없으면 기본값으로 나온다.
title_separator          : "&#124;" # 타이틀 사이 구분자 <title>Welcome to Jekyll | Minimal Mistakes</title> 해당 형식으로 들어갑니다.
subtitle                 : "Version 1.0" # 타이틀 아래에 나올 작은 글씨 
name                     : "이하연" # 맨 하단 이름 찍히는 영역
description              : "하고 싶은 것이 많은 사람" # Meta 태그에 들어가는 영역 
url                      : "https://Hayeon-Lee.github.io/" # GitBlog 호스트 주소
baseurl                  : # subPath https://Hayeon-Lee.github.io/blog라고 하고 싶을 시 "/blog" 라고 적는다.
repository               : "Hayeon-Lee/Hayeon-Lee.github.com" # GitHub username/repo-name  
teaser                   : # "" # 홈페이지 기본 티져 이미지
logo                     : # 타이틀 옆에 작게 들어갈 이미지.
masthead_title           : "한량처럼 살고싶다" # 홈페이지 최 상탄에 들어갈 타이틀
breadcrumbs              : true # 브래드크럼 사용 여부 true, false (default) , _data/ui-text.yml에 다국어 지원 가능합니다.
words_per_minute         : 200 # 해당 포스트 읽는데 걸리는 시간을 계산하기 위해 대락 분당 읽는 수가 몇글자가 될지 적는 공간.

# Site Author
author:
  name             : "이하연" 
  avatar           : "" # 프로필 이미지
  bio              : "열심히 건강하게 살기."
  location         : "Republic of Korea"
  email            : "papepopepe@naver.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      #url: mailto:papepopepe@naver.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.naver.com/papepopepe"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Hayeon-Lee"

# Site Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:papepopepe@naver.com

# Defaults Post들에 적용될 기본 설정들
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
